loadTexts([
    "Uliczna rewolta sposobem na sprowadzenie do Polski islamskich imigrantów",
"Tusk próbuje ingerować w Polskie sprawy",
"Ciamajdan 2",
"Dziś w Polsce każdy może demonstrować, gdy rządził Tusk było inaczej",
"Koniec postkomunizmu w Polsce - niezadowoleni protestują",
"Donald Tusk kolejny raz grozi Polsce",
"Reforma sądu najwyższego uchwalona - Symboliczny koniec postkomunizmu w Polsce",
"Pogarda narzędziem polityki",
"Timmermans, człowiek roku \"Gazety Wyborczej\" znów grozi Polsce",
"Temat / Tytuł",
"Brutalny atak posła Platformy Obywatelskiej Tomasza Lenza na innych parlamentarzystów",
"Prawo i Sprawiedliwość realizuje reformę sądownictwa, którą obiecało Polakom",
"To jest bardzo poważny cios dla PiS ze strony prezydenta",
"Jak manipuluje niemiecka telewizja publiczna",
"Prezydent wchodzi do gry",
"Opozycja chce zablokować reformę SN, która ma wyeliminować korupcję i nadużycia",
"Przewodniczący KRS przeciwny reformie SN, która ma wyeliminować korupcję i nadużycia",
"M. Gersdorf podważa mandat demokratycznie wybranej władzy",
"TVP.info: Sąd Najwyższy łamie konstytucję",
"Klęska niemieckiego państwa: lewackie bojówki zdewastowały Hamburg",
"Bruksela jest politycznym narzędziem Berlina - my musimy robić swoje",
"Brutalny atak Adama Michnika na dziennikarza portalu tvp.info",
"Totalna opozycja domaga się wstrzymania ekshumacji",
"Michał Rachoń - publicysta TVP info",
"Sędzia, handlarz roszczeń  i bierni urzędnicy",
"Problemy z odbiorem sygnału TVP",
"Ogromny sukces rządu: w budżecie państwa nadwyżka zamiast deficytu",
"Donald Trump jak Lech Kaczyński - O Polsce, świecie, bogu i historii",
"Samuel Pereira: Pozują do zdjęcia, to nie są gesty do zgromadzonych",
"Korzystając z pogody - tysiące turystów odwiedziło Krakowskie Przedmieście",
"Będzie was PiS ruchał w dupę, będzie was PiS dymał tak, jak was Platforma nie dymała. Aż was kukle będą swędziały.",
"Próba zablokowania prawdy",
"Media komercyjne walczą z rządem bardziej niż opozycja",
"Timmermans szantażuje Polskę",
"Barbarzyńcy znów próbowali zakłócić modlitwę za ofiary katastrofy",
"Rząd PO-PSL podciął mu skrzydła, dziś Lot ma znakomite wyniki",
"Islamistki też zabijają",
"Hanna Gronkiewicz-Waltz stawia się ponad prawem",
"Bojówki opozycji próbują wedrzeć się na teren polskiego parlamentu",
"Polacy docenili wzruszające słowa Donalda Trumpa o naszej ojczyźnie",
"Świat podziwia Polskę za organizację wielkich wydarzeń",
"Szokujące zapowiedzi opozycyjnych bojówkarzy",
"Platforma obywatelska zapowiada kolejny pucz i majdan w Warszawie",
"Jak nie ulica, to może zagranica",
"Front obrony sędziowskiej kasty",
"Komisja Europejska kolejny raz chce ingerować w wewnętrzne sprawy Polski",
"Prawo i Sprawiedliwość konsekwentnie realizuje obietnice wyborcze",
"Rzecznik Platformy Obywatelskiej, Jan Grabiec kłamie",
"Państwo Tuska oddało 35 milionów złotych gangsterom z Pruszkowa",
"Obrońcy pedofilów i alimenciarzy twarzami oporu przeciwko reformie sądownictwa",
"Donald Trump i państwa trójmorza zmieniają układ sił na świecie",
"M. Gersdorf przeciwna reformie SN, która ma wyeliminować korupcję i nadużycia",
"Platforma Obywatelska niezadowolona ze wzrostu znaczenia Polski na świecie",
"Obrońcy status quo w sądownictwie leżą przed sejmem",
"Ryszard Petru tym razem nie poleciał na Maderę",
"Kot prezesa twardo stawił czoła zwolennikom opozycji",
"Opozycja próbuje zorganizować pucz przeciwko demokratycznie wybranej władzy",
"Przyjaciele Sorosa radzą, jak obalić polski rząd",
"Premier Beata Szydło broni ministra Błaszczaka, odpowiedzialnego za bezpieczeństwo polaków",
"Krzysztof Mieszkowski z Nowoczesnej wykluczony  - przerwa w obradach sejmu",
"Pierwsze czytanie projektu ustawy o SN, która ma wyeliminować korupcję i nadużycia",
"To jest próba wywoływania awantury - nie chodzi tylko o sądy",
"Opozycja próbuje zorganizować pucz przeciwko demokratycznie wybranej władzy / Opozycja zapowiada łamanie prawa / szokujące zapowiedzi opozycyjnych bojówkarzy",
"Słaba frekwencja przed sejmem pomimo nawoływań Grzegorza Schetyny do puczu",
"Młodzi Polacy całkowicie odrzucają Platformę Obywatelską  i Nowoczesną",
"Zagraniczne agencje PR organizują protesty w Polsce",
"Pytanie brzmi na ile ten protest przeciw reformie sądownictwa jest przygotowany, o czym świadczy, że wszyscy mają takie same znicze w rękach",
"Agresja i chamstwo - tyle zapamiętamy z dzisiejszej manifestacji przed sejmem",
"Sondaż poparcia partii politycznych w przedziale wiekowym 18-24 lata",
"Celem opozycji jest dążenie do awantury i do tego, żeby na ulicach trwały bójki",
"O politycznym zaangażowaniu sędziów",
"Astroturfing to atak zaplanowany",
"Gra o to, by było jak było",
"Weto opóźni walkę z nadużyciami sędziów",
"Decyzja prezydenta zawiodła polaków",
"Orędzie",
"Paweł Kukiz: Zostało im darcie japy na ulicach",
"Jedną z zasad postkomunizmu jest zarządzanie przez kulturę - kultura w III RP była sposobem na dyscyplinowanie",
"Polacy wybierają Prawo i Sprawiedliwość, bo najważniejsza jest gospodarka",
"Dzień dobry panie prezesie. Cześć Adrian.",
"Min. Ziobro: Mieliśmy prawo oczekiwać innej decyzji prezydenta",
"Min. Ziobro: Chcemy ograniczyć chorobę korporacji sędziowskiej",
"Złodziejska reprywatyzacja - czas rozliczeń",
"Kompromitujące decyzje, nadużycia i polityczne zaangażowanie części sędziów",
"Konieczność zmian w sądownictwie",
"Min. Ziobro: naszym zadaniem jest zmienić sądownictwo i nikt nam w tym nie przeszkodzi",
"Wybór Donalda Tuska sukcesem Niemiec",
"Powtórka nocnej zmiany",
"Ostatnia walka esbeków",
"Plan opozycji",
"Nieudana próba destabilizacji państwa",
"Uliczna rozróba zamiast pamięci o bohaterach",
"Wolne media według Platformy",
"Standard (nie)demokratyczny",
"Protokół zniszczenia",
"Państwo Polskie odzyskuje godność",
"Polska obnażyła unijne standardy demokracji ",
"Utrudnione relacje dziennikarzy TVP - agresywne reakcje protestujących",
"Kuriozalny raport o Polsce",
"Polityczna nagonka na Piotrowicza",
"Absurdalny atak na premier Beatę Szydło",
"Prezydent przemówił jak trzeba",
"Borys Budka z Platformy Obywatelskiej obrażał ministra Błaszczaka, kpiąc z jego nazwiska",
"Komu przeszkadza Polska",
"Polityczna nagonka na rzecznika MON (Misiewicza - przyp.)",
"TVP Informowała o WOŚP i nie wycinała serduszek. Tajemnicze zniknięcie z kurtki pana Posła musiało być robotą Belzebuba.",
"Prezydent tryska humorem ku czci poległych Powstańców Warszawskich",
"Próba destabilizacji państwa",
"Mimo sporu kompetecyjnego z prezydentem, SN prowadzi sprawę ułaskawienia Kamińskiego",


]);